import { HttpService } from '@nestjs/axios';
import { ConfigurableModuleBuilder, Module, Provider } from '@nestjs/common';
import axios, { CreateAxiosDefaults } from 'axios';

/** How the axios instance behind a named client is configured. */
export type ApiClientOptions = CreateAxiosDefaults;

export const API_CLIENT_OPTIONS = 'API_CLIENT_OPTIONS';

/**
 * A named HTTP client as a plain provider, for modules that already hold their
 * own configuration and would otherwise have to expose it to an imported
 * module just so it could be injected there.
 */
export function createApiClientProvider<T>(client: {
  provide: string;
  inject: any[];
  useFactory: (...args: T[]) => ApiClientOptions;
}): Provider {
  return {
    provide: client.provide,
    useFactory: (...args: T[]) =>
      new HttpService(axios.create(client.useFactory(...args))),
    inject: client.inject,
  };
}

interface ApiModuleExtras {
  /**
   * Injection token the client is exposed under. Given at registration time
   * rather than resolved asynchronously, because the module has to know what
   * to provide and export before any factory runs.
   */
  name: string;
}

/**
 * `register`/`registerAsync` and every options shape they accept — including
 * `useClass`, `useExisting` and `useFactory` — are generated by Nest instead of
 * being hand-written.
 */
const { ConfigurableModuleClass } = new ConfigurableModuleBuilder<ApiClientOptions>({
  optionsInjectionToken: API_CLIENT_OPTIONS,
})
  .setClassMethodName('register')
  .setExtras<ApiModuleExtras>({ name: '' }, (definition, extras) => ({
    ...definition,
    providers: [
      ...(definition.providers ?? []),
      {
        provide: extras.name,
        // Its own axios instance rather than `HttpModule.register`: a named
        // client exists precisely so its baseURL and timeouts stay independent
        // from every other caller's.
        useFactory: (options: ApiClientOptions) =>
          new HttpService(axios.create(options)),
        inject: [API_CLIENT_OPTIONS],
      },
    ],
    exports: [extras.name],
  }))
  .build();

/**
 * Registers a named HTTP client, so a consumer injects the service it talks to
 * (`@Inject(USERS_SERVICE_CLIENT)`) instead of a shared, unconfigured one.
 */
@Module({})
export class ApiModule extends ConfigurableModuleClass {}
