services:
  postgres:
    image: postgres:16
    container_name: admin-back-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finances
    ports:
      - '5433:5432'
    volumes:
      - admin-back-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh

volumes:
  admin-back-postgres-data:
