/**
 * Stable, client-facing domain error codes (RF-14). This constant is the single
 * source of truth for the strings the API exposes: exceptions carry them and the
 * exception filter surfaces them verbatim, so a consumer can branch on `code`
 * without parsing prose. Adding a code is additive; changing the HTTP status a
 * code maps to is a breaking change (new API version, RNF-8).
 */
export const LEDGER_ERROR_CODE = {
  // Transactions
  UNBALANCED_TRANSACTION: 'UNBALANCED_TRANSACTION',
  INSUFFICIENT_POSTINGS: 'INSUFFICIENT_POSTINGS',
  IMMUTABLE_TRANSACTION: 'IMMUTABLE_TRANSACTION',
  INVALID_TRANSACTION_STATE: 'INVALID_TRANSACTION_STATE',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  NOT_A_TRANSFER_PAIR: 'NOT_A_TRANSFER_PAIR',
  PENDING_LEG_NOT_FOUND: 'PENDING_LEG_NOT_FOUND',

  // Accounts
  ACCOUNT_CLOSED: 'ACCOUNT_CLOSED',
  ACCOUNT_ALREADY_CLOSED: 'ACCOUNT_ALREADY_CLOSED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  CURRENCY_NOT_ALLOWED: 'CURRENCY_NOT_ALLOWED',
  NAME_COLLISION: 'NAME_COLLISION',
  SYSTEM_ACCOUNT_PROTECTED: 'SYSTEM_ACCOUNT_PROTECTED',
  REAL_ACCOUNT_SINGLE_CURRENCY: 'REAL_ACCOUNT_SINGLE_CURRENCY',
  ROOT_TYPE_IMMUTABLE: 'ROOT_TYPE_IMMUTABLE',
  INVALID_ACCOUNT_NAME: 'INVALID_ACCOUNT_NAME',
  INVALID_CLOSE_DATE: 'INVALID_CLOSE_DATE',

  // Reconciliation
  ASSERTION_NOT_FOUND: 'ASSERTION_NOT_FOUND',
  ASSERTION_ALREADY_REVOKED: 'ASSERTION_ALREADY_REVOKED',
  ASSERTION_NOT_EVALUABLE: 'ASSERTION_NOT_EVALUABLE',
  ASSERTION_CURRENCY_MISMATCH: 'ASSERTION_CURRENCY_MISMATCH',
  DISCREPANCY_NOT_RESOLVABLE: 'DISCREPANCY_NOT_RESOLVABLE',

  // Ledger settings and reference data
  LEDGER_NOT_INITIALIZED: 'LEDGER_NOT_INITIALIZED',
  LEDGER_ALREADY_INITIALIZED: 'LEDGER_ALREADY_INITIALIZED',
  INVALID_CURRENCY_CODE: 'INVALID_CURRENCY_CODE',
  INVALID_TIME_ZONE: 'INVALID_TIME_ZONE',
  INVALID_MINOR_UNITS: 'INVALID_MINOR_UNITS',
  CURRENCY_PRECISION_CONFLICT: 'CURRENCY_PRECISION_CONFLICT',
  UNKNOWN_CURRENCY: 'UNKNOWN_CURRENCY',

  // Value objects
  INVALID_MONEY: 'INVALID_MONEY',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  MONEY_SCALE: 'MONEY_SCALE',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_LEDGER_DATE: 'INVALID_LEDGER_DATE',
  INVALID_PAYEE: 'INVALID_PAYEE',

  // Platform (§3.8, RF-26)
  DUPLICATE_EXTERNAL_REF: 'DUPLICATE_EXTERNAL_REF',
  CONCURRENCY_CONFLICT: 'CONCURRENCY_CONFLICT',
  MISSING_AUTH_CONTEXT: 'MISSING_AUTH_CONTEXT',
  UNREGISTERED_COMMAND: 'UNREGISTERED_COMMAND',
  UNREGISTERED_QUERY: 'UNREGISTERED_QUERY',
  UNKNOWN_EVENT_TYPE: 'UNKNOWN_EVENT_TYPE',
} as const;

/** Union of every stable RF-14 code. */
export type LedgerErrorCode = (typeof LEDGER_ERROR_CODE)[keyof typeof LEDGER_ERROR_CODE];
