export const AUTH_MODULE_OPTIONS = 'AUTH_MODULE_OPTIONS';
export const USERS_SERVICE_CLIENT = 'USERS_SERVICE_CLIENT';
export const JWT_STRATEGY_OPTIONS = 'JWT_STRATEGY_OPTIONS';
export const OIDC_DISCOVERY_CACHE = 'OIDC_DISCOVERY_CACHE';
